WITH CTE AS (
SELECT
split_part(transaction_code,'-',1) AS bank,
MONTHNAME(DATE(transaction_date,'dd/MM/yyyy hh24:mi:ss')) as month,
SUM(value) as value,
ROW_NUMBER() OVER (PARTITION BY MONTH ORDER BY SUM(VALUE) DESC) AS RNK
FROM PD2023_WK01
GROUP BY split_part(transaction_code,'-',1),
MONTHNAME(DATE(transaction_date,'dd/MM/yyyy hh24:mi:ss'))
)

, AVG_RANK AS (
SELECT
BANK,
AVG(RNK) AS AVG_RANK_PER_BANK
FROM CTE
GROUP BY BANK
)

, AVG_TRANSACTION_VALUE AS (
SELECT
AVG(VALUE) AS AVG_TRANSACTION_VALUE_PER_RANK,
RNK
FROM CTE
GROUP BY RNK
)

SELECT 
MONTH AS TRANSACTION_DATE,
CTE.BANK,
VALUE,
CTE.RNK AS BANK_RANK_PER_MONTH,
AVG_RANK_PER_BANK,
AVG_TRANSACTION_VALUE_PER_RANK
FROM CTE
INNER JOIN AVG_RANK AS AR ON CTE.BANK=AR.BANK
INNER JOIN AVG_TRANSACTION_VALUE AS ATV ON CTE.RNK=ATV.RNK